/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Usercomonents: (typeof import('./src/components/user/UserComonents.vue'))['default']
    UserComonents: typeof import('./src/components/user/UserComonents.vue')['default']
    Usercpmonets: (typeof import('./src/components/user/UserComonents.vue'))['default']
    UserUserComonents: typeof import('./src/components/user/UserComonents.vue')['default']
  }
}
